name: CI workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            gcc \
            g++ \
            libpq-dev \
            libffi-dev \
            libssl-dev \
            build-essential \
            pkg-config \
            libgirepository1.0-dev \
            libcairo2-dev \
            dbus \
            libdbus-1-dev \
            python3-dev \
            python3-gi \
            git \
            curl \
            ca-certificates
          apt-get clean
          rm -rf /var/lib/apt/lists/*

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: |
          pip install nose
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

